FROM minio/mc:latest

# Copy the initialization script
COPY minio-init.sh /usr/local/bin/minio-init.sh

# Make the script executable
RUN tr -d '\r' < /usr/local/bin/minio-init.sh > /tmp/minio-init.sh \
    && mv /tmp/minio-init.sh /usr/local/bin/minio-init.sh \
    && chmod +x /usr/local/bin/minio-init.sh

# Set the entrypoint to run our initialization script
ENTRYPOINT ["sh", "/usr/local/bin/minio-init.sh"]
